# Generated by Django 3.1.7 on 2021-03-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='first_name',
            field=models.CharField(default='na', max_length=30),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='last_name',
            field=models.CharField(default='na', max_length=30),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='password2',
            field=models.CharField(default='na', max_length=9),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='email',
            field=models.EmailField(default='na', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='password',
            field=models.CharField(default='na', max_length=9),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='username',
            field=models.CharField(default='na', max_length=25),
        ),
    ]
